
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `temptation` DEFAULT CHARACTER SET utf8 ;
USE `temptation` ;

CREATE TABLE IF NOT EXISTS 'guides' (
    'id' INT NOT NULL AUTO_INCREMENT,
    'name' VARCHAR(50) NOT NULL,
    'email' VARCHAR(30) NOT NULL,
    'phone' VARCHAR(20) NOT NULL,
    'rating' DECIMAL(5) NOT NULL,
    PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1001;

CREATE TABLE IF NOT EXISTS 'customers' (
    'id' INT NOT NULL AUTO_INCREMENT,
    'name' VARCHAR(50) NOT NULL,
    'email' VARCHAR(30) NOT NULL,
    'phone' VARCHAR(20) NOT NULL,
    'rating' DECIMAL(5) NOT NULL,
    PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1001;

CREATE TABLE IF NOT EXISTS 'events' (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guide_id` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `kind` VARCHAR(30) NOT NULL,
  `duration` DECIMAL(5) NOT NULL,
  `max_number_participant` DECIMAL(5) NOT NULL,
  `min_number_participant` DECIMAL(5) NOT NULL,
  `route` VARCHAR(30) NOT NULL,
  `details` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1001;

ALTER TABLE 'events'
ADD FOREIGN KEY ('guide_id') REFERENCES 'guides'('id');

CREATE TABLE IF NOT EXISTS 'offers' (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `date_creation` CURRENT_DATE NOT NULL,
  `date_start` DATE NOT NULL,
  `coast` DECIMAL(20) NOT NULL,
  `ticket_amount` DECIMAL(5) NOT NULL,
  PRIMARY KEY (`id`)
  FOREIGN KEY (`event_id`) REFERENCES 'events' ('id')
)
ENGINE = InnoDB
AUTO_INCREMENT = 1001;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;