SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS 'internet_store' DEFAULT CHARACTER SET utf8 ;
USE 'internet_store' ;

CREATE TABLE IF NOT EXISTS 'customers' (
  ID Customer INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(45) NOT NULL,
  Surname VARCHAR(45) NOT NULL,
  Address VARCHAR(250) NOT NULL,
  Email VARCHAR(45) NOT NULL,
  Phone Number VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID Customer))
ENGINE = InnoDB;
AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS 'products' (
  ID Product INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(100) NOT NULL,
  Description VARCHAR(250) NOT NULL,
  Price DECIMAL(10) NOT NULL,
  PRIMARY KEY (ID Product))
ENGINE = InnoDB;
AUTO_INCREMENT = 1002;

CREATE TABLE IF NOT EXISTS 'order' (
  ID Order INT NOT NULL AUTO_INCREMENT,
  ID Customer INT NOT NULL,
  ID Product INT NOT NULL,
  Order price DECIMAL(10) NOT NULL,
  PRIMARY KEY (ID Order),
  INDEX Customers_idx (ID Customer ASC) VISIBLE,
  INDEX Products_idx (ID Product ASC) VISIBLE,
  CONSTRAINT Customers
    FOREIGN KEY (ID Customer)
    REFERENCES Internet_Store.Customers (ID Customer)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT Products
    FOREIGN KEY (ID Product)
    REFERENCES Internet_Store.Products (ID Product)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;
AUTO_INCREMENT = 1002;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;