SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=1;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=1;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `Targets list` DEFAULT CHARACTER SET utf8 ;
USE `Targets list` ;

CREATE TABLE IF NOT EXISTS `targets` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `target_name` VARCHAR(200) NOT NULL,
  `target_description` VARCHAR(100) NOT NULL,
  `target_deadline` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_first_name` VARCHAR(200) NOT NULL,
  `user_last_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

CREATE TABLE IF NOT EXISTS `targets_board` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `target_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `target_added_date` DATETIME NOT NULL,
  `target_date_of_completion` DATETIME,
PRIMARY KEY (`id`)
)
ENGINE = InnoDB
AUTO_INCREMENT = 1;

ALTER TABLE `targets_board`
ADD FOREIGN KEY (`target_id`) REFERENCES `targets`(`id`);

ALTER TABLE `targets_board`
ADD FOREIGN KEY (`user_id`) REFERENCES `users`(`id`);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;